### ISSUE TITLE
Add endpoint DELETE /playlist/[playlistId]

### ISSUE THREAD

**Issue by Insire** [Insire/MonstercatNet#8]
[See](https://github.com/defvs/connect-v2-docs/wiki/Playlists#deleting-a-playlist-delete-playlistplaylistid)

- should include unit tests for validating the request in memory
- should include integration/live test for executing the request against the actual monstercat api

**Comment by matheuscr30** [comment]
Can I do this in the Hacktoberfest?

**Comment by Insire** [comment]
Sure thing :)
If you got any questions, feel free to ask.

**Comment by matheuscr30** [comment]
Ok, can I do more than one?

**Comment by Insire** [comment]
There is no limit to how many PRs you can do.

**Comment by Insire** [comment]
Hey @matheuscr30 you are pretty early with this. If you want this PR to count towards your hacktoberfest contributions, then you'll have to open the PR between 1 and 31 of October as described [here](https://hacktoberfest.digitalocean.com/details#rules).

Do you want me to take a look anyway?

**Comment by matheuscr30** [comment]
Yeah, I know. I'm not doing this now, just separating the issues to solve in October 😉

**Comment by Insire** [comment]
Ok? I guess i can simply not merge the PR until then, but its not going to count towards the Hacktoberfest event participation regardless.
